### PR TITLE
Add basic CORS functionality to support testing (WIP)

### PR DESCRIPTION
**Pull request by ljaenicke**
Added basic CORS funcationality by adding fastify-cors.
Allow localhost to access, this fits the most basic test setup.

See Issue #57

### CODE REVIEW

**Review by tschmidtb51 — COMMENTED** [review]
I think the approach is good. We might need a test for this as well.

**Comment by ljaenicke** [comment]
I have updated the pull request.

**Comment by ljaenicke** [comment]
Received failure messages from the workflow, failed to reproduce in my setup (manually)...

**Comment by ljaenicke** [comment]
This is really odd. The list of tests has been extended from 86 to 88 by the two additional CORS tests. Yet, the output shows error code 86 (86 test cases failed).
Note: when running the test manually it fails if the server is not started, but then it should fail with return code 88 after the pull.
image

**Comment by ljaenicke** [comment]
Somehow the github branch and my development environment went out of sync.
Rebased on the latest main branch and updated the PR.

**Comment by tschmidtb51** [comment]
@ljaenicke It looks like you didn't commit your package-lock.json. Therefore, the run fails.

**Comment by tschmidtb51** [comment]
@secvisogram/service-dev Is the current suggested implementation sufficient or is something missing? Any other comments to the PR?

**Comment by ljaenicke** [comment]
> @ljaenicke It looks like you didn't commit your package-lock.json. Therefore, the run fails.

That hint was important. Needed to perform a "npm cache clean --force" in my working directory to reproduce. I have created a fixup commit adding the changes needed in package-lock.json.

**Comment by tschmidtb51** [comment]
@StefanNemeth/ @reneschultheis  (in place for @secvisogram/service-dev) Please also resolve merge conflicts during review.

**Comment by MarcoKorinth** [comment]
LGTM. 
Branch with resolved merge conflicts were merged in PR #66

**Comment by tschmidtb51** [comment]
> LGTM. Branch with resolved merge conflicts were merged in PR #66

@MarcoKorinth Was that the implicit answer to the [question](https://github.com/secvisogram/csaf-validator-service/pull/58#issuecomment-1555056096) below?

> https://github.com/orgs/secvisogram/teams/service-dev  Is the current suggested implementation sufficient or is something missing? Any other comments to the PR?

Or was there anything missing resp. should/could be improved?

**Comment by MarcoKorinth** [comment]
> > LGTM. Branch with resolved merge conflicts were merged in PR #66
> 
> @MarcoKorinth Was that the implicit answer to the [question](https://github.com/secvisogram/csaf-validator-service/pull/58#issuecomment-1555056096) below?
> 
> > https://github.com/orgs/secvisogram/teams/service-dev  Is the current suggested implementation sufficient or is something missing? Any other comments to the PR?
> 
> Or was there anything missing resp. should/could be improved?

@tschmidtb51 yes this was supposed to be an implicit answer.
In my opinion the implementation is sufficient.

**Pull request merged**
